<h1>Homework 2</h1>
In this notebook there are the activities related to the second homework and, as with the first homework, feel free to use the web to find the solutions to any of these problems. Also, the bonus questions are not mandatory but, if you happen to have the time, try them out too!<br>



<h1>numpy</h1>
Exercise 1: show that now you can import libraries by importing pandas, numpy and matplotlib.

In [6]:
import pandas as pd
import numpy as np
import matplotlib as matp

In [7]:
pd

<module 'pandas' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [8]:
np

<module 'numpy' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [9]:
matp

<module 'matplotlib' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\matplotlib\\__init__.py'>

Exercise 2: Will the following code block work?  

In [10]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
#ANSWER: this code will work because, although the arrays have different size, one of the dimensions' items has a value of 1
array1 = np.random.random((3, 3))
array2 = np.random.random((3, 1))

np.add(array1,array2)

array([[0.83015204, 0.60612729, 0.74573233],
       [1.55848292, 1.45169061, 1.23168008],
       [0.65207542, 1.28402823, 0.94813683]])

Exercise 3: What about now?

In [11]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array3 = np.random.random((3, 3))
array4 = np.random.random((3, 2))

np.add(array3,array4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [12]:
array3

array([[0.04249108, 0.46453865, 0.40868492],
       [0.56390641, 0.84127704, 0.66341858],
       [0.396626  , 0.20610405, 0.04837571]])

In [13]:
array4

array([[0.59654218, 0.56381284],
       [0.75289399, 0.87717302],
       [0.58226801, 0.3990749 ]])

Exercise 4: by inspecting the arrays 1 to 4 can you figure out why one operation worked and another one didn't? (hint: check their values and shape)

In [ ]:
# According to Numpy documentation (broadcasting rules), two arrays are compatible when their dimensions are equal (i.e. a[3,3] and b[3,3]) or one of them
#is 1. In exercise 2, array2 has a dimension with value 1, therefore, it its compatible with array1 and the addition is possible
# In exercise 3,however, the arrays have different shapes and none of their dimensions is 1, indicating that the arrays are incompatible.  

In [ ]:
#reference: https://numpy.org/doc/stable/user/basics.broadcasting.html ; https://www.statology.org/operands-could-not-be-broadcast-together-with-shapes/

Exercise 5: Using the function to create an array of random numbers [np.random.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) how can you modify the code (as in the cells above) so that the numbers will vary between 0 and 100 instead of 0 and 1? And how can you modify the shape of the function?

In [14]:
# To create an array with random numbers from 1 to 100: 
from numpy import random 
random

<module 'numpy.random' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [111]:
# To create an array with random numbers from 1 to 100:
array4 = random.randint(100, size=(3,2))
array4

array([[31,  2],
       [25, 12],
       [74, 78]])

In [112]:
#to change the shape of array4:
new_array4 = array4.reshape(2,3) 
new_array4

array([[31,  2, 25],
       [12, 74, 78]])

In [ ]:
#QUESTION: given the actual sizes of both arrays, is there any method to add array3+array4? I tried to broadcast array4
# but still got an error.

Exercise 6: Using the array defined on the exercise above, use [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) to find the positions the values that are larger than 50 (or feel free to pick any other number).

In [113]:
import numpy as np

In [116]:
np.where(new_array4>50)         #QUESTION: why does this code line have two arrays on its output?

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

<h1>Pandas </h1>
There are two datasets on available to this work, one is the pokemon dataset we explored in the lecture and the other one is the same dataframe but, for the sake of a nice story, let us say it was sabotaged by team rocket.

Exercise 1: open both dataframes supplied using [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) (and don't forget to assign them to different objects).

In [19]:
import pandas as pd
import matplotlib.pyplot as plt 
pd

<module 'pandas' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [20]:
plt

<module 'matplotlib.pyplot' from 'C:\\Users\\melis\\anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py'>

In [21]:
pokemon_df = pd.read_csv('Pokemon.csv')
pokemon_df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [22]:
pokemonsbg_df = pd.read_csv('Pokemon_sabotage.csv')
pokemonsbg_df

#                   Name   Type 1  Type 2  Total    HP  Attack  \
0      1              Bulbasaur    Grass  Poison    318  45.0      49   
1      2                Ivysaur    Grass  Poison    405  60.0      62   
2      3               Venusaur    Grass  Poison    525  80.0      82   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80.0     100   
4      4             Charmander     Fire     NaN    309  39.0      52   
..   ...                    ...      ...     ...    ...   ...     ...   
795  719                Diancie     Rock   Fairy    600  50.0     100   
796  719    DiancieMega Diancie     Rock   Fairy    700  50.0     160   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80.0     110   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80.0     160   
799  721              Volcanion     Fire   Water    600  80.0     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       49.0       65     65.0   45.0           1      False  
1       63.0       80     80.0   60.0           1      False  
2       83.0      100    100.0   80.0           1      False  
3      123.0      122    120.0   80.0           1      False  
4       43.0       60     50.0   65.0           1      False  
..       ...      ...      ...    ...         ...        ...  
795    150.0      100    150.0   50.0           6       True  
796    110.0      160    110.0  110.0           6       True  
797     60.0      150    130.0   70.0           6       True  
798     60.0      170    130.0   80.0           6       True  
799    120.0      130     90.0   70.0           6       True  

[800 rows x 13 columns]

Exercise 2: Using [pd.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) check how many missing numbers are in each dataframe.

In [23]:
pokemon_df.isna   #Missing numbers in Pokemon data frame

<bound method DataFrame.isna of        #                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp

In [79]:
pokemonsbg_df.isna       #Missing numbers in Pokemon Sabotage data frame

<bound method DataFrame.isna of        #                   Name   Type 1  Type 2  Total    HP  Attack  \
0      1              Bulbasaur    Grass  Poison    318  45.0      49   
1      2                Ivysaur    Grass  Poison    405  60.0      62   
2      3               Venusaur    Grass  Poison    525  80.0      82   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80.0     100   
4      4             Charmander     Fire     NaN    309  39.0      52   
..   ...                    ...      ...     ...    ...   ...     ...   
795  719                Diancie     Rock   Fairy    600  50.0     100   
796  719    DiancieMega Diancie     Rock   Fairy    700  50.0     160   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80.0     110   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80.0     160   
799  721              Volcanion     Fire   Water    600  80.0     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       49.0       65     65

Exercise 3: Two of the main ways to deal with missing data is [pd.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) and [pd.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html). How are these methods different from each other in how they deal with the missing data? Which, if any, would you use on the dataset? Why?

In [117]:
#ANSWER: the difference between pd.dropna and pd.fillna. is that pd.dropna deletes all the rows that contain a NaN or Null value,
# while pd.fillna replaces those NaN or Null values with a given value set by us. 
# Personally, I think removing entire rows just because one single value is NaN or Null might cause us a significant loss of 
#information, specially if we have many entries with such values. For this reason, I'd rather use pd.fillna on the dataset, setting 
#the mean value of the whole column as its argument so it will not change the central tendency measures. 
# Of course, this decision will mostly depend on what we are asked to do with the data and the specific questions we want to draw    
# from it.

From now on we will only be working with the main (non sabotaged dataframe).<br>

Exercise 4: to free up memory delete the sabotaged dataframe. Bonus: before deleting find a way to check how much space in memory the dataframes occupy. [hint](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)

In [24]:
import sys
x = pokemonsbg_df
y = pokemon_df
sys.getsizeof(x) , sys.getsizeof(y) #Pokemon sabotage df occupies 199.270 bits, Pokemon df occupies 199.405 bits

(199279, 199405)

In [25]:
del pokemonsbg_df

Exercise 5: Create a new column that contains the sum of the Attack, speed and defense stats.

In [27]:
pokemon_df['Attack+Speed+Def'] = pokemon_df['Attack']+pokemon_df['Speed']+pokemon_df['Defense']
pokemon_df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Attack+Speed+Def  
0         65       65     45           1      False               143  
1         80       80     60           1      False               185  
2        100      100     80           1      False               245  
3        122      120     80           1      False               303  
4         60       50     65           1      False               160  
..       ...      ...    ...         ...        ...               ...  
795      100      150     50           6       True               300  
796      160      110    110           6       True               380  
797      150      130     70           6       True               240  
798      170      130     80           6       True               300  
799      130       90     70           6       True               300  

[800 rows x 14 columns]

Exercise 6: Find out the mean value of the attack, speed, defense columns and the new column that was created above.

In [35]:
pokemon_df[['Attack','Speed','Defense','Attack+Speed+Def']].mean()

Attack               79.00125
Speed                68.27750
Defense              73.84250
Attack+Speed+Def    221.12125
dtype: float64

Exercise 7: Find out how many pokemon have above average stats in the attack, speed, defense and the new column. Bonus: Do the pokemon with above average stats have a preffered type?

In [69]:
pokemon_df[pokemon_df['Attack'] > 79.00125].value_counts

<bound method DataFrame.value_counts of        #                       Name   Type 1  Type 2  Total  HP  Attack  \
2      3                   Venusaur    Grass  Poison    525  80      82   
3      3      VenusaurMega Venusaur    Grass  Poison    625  80     100   
6      6                  Charizard     Fire  Flying    534  78      84   
7      6  CharizardMega Charizard X     Fire  Dragon    634  78     130   
8      6  CharizardMega Charizard Y     Fire  Flying    634  78     104   
..   ...                        ...      ...     ...    ...  ..     ...   
795  719                    Diancie     Rock   Fairy    600  50     100   
796  719        DiancieMega Diancie     Rock   Fairy    700  50     160   
797  720        HoopaHoopa Confined  Psychic   Ghost    600  80     110   
798  720         HoopaHoopa Unbound  Psychic    Dark    680  80     160   
799  721                  Volcanion     Fire   Water    600  80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendar

In [70]:
pokemon_df[pokemon_df['Speed'] > 68.27750].value_counts

<bound method DataFrame.value_counts of        #                       Name   Type 1  Type 2  Total   HP  Attack  \
2      3                   Venusaur    Grass  Poison    525   80      82   
3      3      VenusaurMega Venusaur    Grass  Poison    625   80     100   
5      5                 Charmeleon     Fire     NaN    405   58      64   
6      6                  Charizard     Fire  Flying    534   78      84   
7      6  CharizardMega Charizard X     Fire  Dragon    634   78     130   
..   ...                        ...      ...     ...    ...  ...     ...   
794  718           Zygarde50% Forme   Dragon  Ground    600  108     100   
796  719        DiancieMega Diancie     Rock   Fairy    700   50     160   
797  720        HoopaHoopa Confined  Psychic   Ghost    600   80     110   
798  720         HoopaHoopa Unbound  Psychic    Dark    680   80     160   
799  721                  Volcanion     Fire   Water    600   80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generati

In [73]:
pokemon_df[pokemon_df['Defense'] > 73.84250].value_counts

<bound method DataFrame.value_counts of        #                       Name  Type 1  Type 2  Total   HP  Attack  \
2      3                   Venusaur   Grass  Poison    525   80      82   
3      3      VenusaurMega Venusaur   Grass  Poison    625   80     100   
6      6                  Charizard    Fire  Flying    534   78      84   
7      6  CharizardMega Charizard X    Fire  Dragon    634   78     130   
8      6  CharizardMega Charizard Y    Fire  Flying    634   78     104   
..   ...                        ...     ...     ...    ...  ...     ...   
793  717                    Yveltal    Dark  Flying    680  126     131   
794  718           Zygarde50% Forme  Dragon  Ground    600  108     100   
795  719                    Diancie    Rock   Fairy    600   50     100   
796  719        DiancieMega Diancie    Rock   Fairy    700   50     160   
799  721                  Volcanion    Fire   Water    600   80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendar

In [74]:
pokemon_df[pokemon_df['Attack+Speed+Def'] > 221.12125].value_counts    

<bound method DataFrame.value_counts of        #                       Name   Type 1  Type 2  Total  HP  Attack  \
2      3                   Venusaur    Grass  Poison    525  80      82   
3      3      VenusaurMega Venusaur    Grass  Poison    625  80     100   
6      6                  Charizard     Fire  Flying    534  78      84   
7      6  CharizardMega Charizard X     Fire  Dragon    634  78     130   
8      6  CharizardMega Charizard Y     Fire  Flying    634  78     104   
..   ...                        ...      ...     ...    ...  ..     ...   
795  719                    Diancie     Rock   Fairy    600  50     100   
796  719        DiancieMega Diancie     Rock   Fairy    700  50     160   
797  720        HoopaHoopa Confined  Psychic   Ghost    600  80     110   
798  720         HoopaHoopa Unbound  Psychic    Dark    680  80     160   
799  721                  Volcanion     Fire   Water    600  80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendar

In [84]:
column_Attack = pokemon_df['Attack']
column_speed = pokemon_df['Speed']
column_defense = pokemon_df['Defense']
column_AttackSpeedDef = pokemon_df['Attack+Speed+Def'] 

In [85]:
#Other way to count the number of Pokemons with above-average stats in the attack, speed,defense and the Attack+Speed+Def column 
#could be:
count_attack = column_Attack[column_Attack > 79.00125].count()
count

378

In [97]:
count_speed=column_speed[column_speed> 68.27750].count()
count_speed

376

In [99]:
count_defense=column_defense[column_defense> 73.84250].count()
count_defense

352

In [100]:
count_AttackSpeedDef=column_AttackSpeedDef[column_AttackSpeedDef> 221.12125].count()
count_AttackSpeedDef

390

Super bonus: There are many platforms out there that contain different tools to boost your learning. Then for the super bonus create an account on [kaggle](https://www.kaggle.com/) and complete the courses
[intro to programming](https://www.kaggle.com/learn/intro-to-programming) and [intro to python](https://www.kaggle.com/learn/python) courses. All kaggle courses are free of charge and offer a [certificate](https://www.kaggle.com/learn-course-certificates) !

In [118]:
#registered and started: Intro to programming! :)